@baseurl = https://8080-gurincha-listalivros-2u594r7a9c4.ws-us114.gitpod.io

###
GET {{baseurl}}/meio_de_leitura

###
POST {{baseurl}}/meio_de_leitura
Content-Type: application/json

{
    "meio_de_leitura": "Livro Fisico",
}

###
POST {{baseurl}}/meio_de_leitura
Content-Type: application/json

{
    "meio_de_leitura": "Livro Digital",

}

###
DELETE {{baseurl}}/meio_de_leitura/2